# South Province
from model.Pokemon import Pokemon


south_area_one = {
    'name': 'South Province (Area One)',
    'key': 'south_area_one',
    'encounters': [
        Pokemon('Psyduck', False, False, 0, False),
        Pokemon('Hoppip', False, False, 0, False),
        Pokemon('Sunkern', False, False, 0, False),
        Pokemon('Ralts', False, False, 0, False),
        Pokemon('Wingull', False, False, 0, False),
        Pokemon('Azurill', False, False, 0, False),
        Pokemon('Buizel', False, False, 0, False),
        Pokemon('Fletchling', False, False, 0, False),
        Pokemon('Scatterbug', False, False, 0, False),
        Pokemon('Lechonk', False, False, 0, False),
        Pokemon('Igglybuff', False, False, 0, False),
        Pokemon('Wooper', False, False, 0, False),
        Pokemon('Bounsweet', False, False, 0, False),
        Pokemon('Bonsly', False, False, 0, False),
        Pokemon('Skwovet', False, False, 0, False),
        Pokemon('Shroodle', False, False, 0, False),
        Pokemon('Flamigo', False, False, 0, False),
        Pokemon('Drowzee', False, False, 0, False),
        Pokemon('Happiny', False, False, 0, False),
        Pokemon('Fidough', False, False, 0, False),
        Pokemon('Fletchinder', False, False, 0, False),
        Pokemon('Gastly', False, False, 0, False),
        Pokemon('Vigoroth', False, False, 0, False),
        Pokemon('Combee', False, False, 0, False),
        Pokemon('Pichu', False, False, 0, False),
        Pokemon('Deerling', False, False, 0, False),
        Pokemon('Chewtle', False, False, 0, False),
        Pokemon('Oricorio', False, False, 0, False),
        Pokemon('Spewpa', False, False, 0, False),
        Pokemon('Pachirisu', False, False, 0, False),
        Pokemon('Gimmighoul', False, False, 0, False),
        Pokemon('Magikarp', False, False, 0, False),
        Pokemon('Wiglett', False, False, 0, False),
        Pokemon('Surskit', False, False, 0, False),
    ]
}
south_area_two = {
    'name': 'South Province (Area Two)',
    'key': 'south_area_two',
    'encounters': [
        Pokemon('Mareep', False, False, 0, False),
        Pokemon('Hoppip', False, False, 0, False),
        Pokemon('Pikachu', False, False, 0, False),
        Pokemon('Meowth', False, False, 0, False),
        Pokemon('Maschiff', False, False, 0, False),
        Pokemon('Smoliv', False, False, 0, False),
        Pokemon('Skwovet', False, False, 0, False),
        Pokemon('Fletchling', False, False, 0, False),
        Pokemon('Pichu', False, False, 0, False),
        Pokemon('Diglett', False, False, 0, False),
        Pokemon('Combee', False, False, 0, False),
        Pokemon('Vespiquen', False, False, 0, False),
        Pokemon('Kricketot', False, False, 0, False),
        Pokemon('Makuhita', False, False, 0, False),
        Pokemon('Nacli', False, False, 0, False),
        Pokemon('Chewtle', False, False, 0, False),
        Pokemon('Fletchling', False, False, 0, False),
        Pokemon('Bronzor', False, False, 0, False),
        Pokemon('Happiny', False, False, 0, False),
        Pokemon('Fidough', False, False, 0, False),
        Pokemon('Tinkatink', False, False, 0, False),
        Pokemon('Starly', False, False, 0, False),
        Pokemon('Staravia', False, False, 0, False),
        Pokemon('Sunkern', False, False, 0, False),
        Pokemon('Rockruff', False, False, 0, False),
        Pokemon('Igglybuff', False, False, 0, False),
        Pokemon('Jigglypuff', False, False, 0, False),
        Pokemon('Misdreavus', False, True, 0, False),
        Pokemon('Gimmighoul', False, False, 0, False)
    ]
}
south_area_three = {
    'name': 'South Province (Area Three)',
    'key': 'south_area_three',
    'encounters': [
        Pokemon('Growlithe', False, False, 0, False),
        Pokemon('Gastly', False, False, 0, False),
        Pokemon('Drowzee', False, False, 0, False),
        Pokemon('Magikarp', False, False, 0, False),
        Pokemon('Skiploom', False, False, 0, False),
        Pokemon('Murkrow', False, False, 0, False),
        Pokemon('Misdreavus', False, True, 0, False),
        Pokemon('Dunsparce', False, False, 0, False),
        Pokemon('Stantler', False, False, 0, False),
        Pokemon('Shroomish', False, False, 0, False),
        Pokemon('Slakoth', False, False, 0, False),
        Pokemon('Vigoroth', False, False, 0, False),
        Pokemon('Makuhita', False, False, 0, False),
        Pokemon('Gulpin', False, True, 0, False),
        Pokemon('Spoink', False, False, 0, False),
        Pokemon('Swablu', False, False, 0, False),
        Pokemon('Zangoose', False, False, 0, False),
        Pokemon('Seviper', False, False, 0, False),
        Pokemon('Bagon', False, True, 0, False),
        Pokemon('Shinx', False, False, 0, False),
        Pokemon('Luxio', False, False, 0, False),
        Pokemon('Pachirisu', False, False, 0, False),
        Pokemon('Drifloon', True, False, 0, False),
        Pokemon('Stunky', True, False, 0, False),
        Pokemon('Bronzor', False, False, 0, False),
        Pokemon('Happiny', False, False, 0, False),
        Pokemon('Basculin', False, False, 0, False),
        Pokemon('Deerling', False, False, 0, False),
        Pokemon('Axew', False, False, 0, False),
        Pokemon('Rufflet', False, False, 0, False),
        Pokemon('Braviary', False, False, 0, False),
        Pokemon('Fletchinder', False, False, 0, False),
        Pokemon('Litleo', False, False, 0, False),
        Pokemon('Skiddo', False, False, 0, False),
        Pokemon('Goomy', False, False, 0, False),
        Pokemon('Yungoos', False, False, 0, False),
        Pokemon('Gumshoos', False, False, 0, False),
        Pokemon('Rookidee', False, False, 0, False),
        Pokemon('Corvisquire', False, False, 0, False),
        Pokemon('Lechonk', False, False, 0, False),
        Pokemon('Oinkologne', False, False, 0, False),
        Pokemon('Tarountula', False, False, 0, False),
        Pokemon('Nymble', False, False, 0, False),
        Pokemon('Pawmi', False, False, 0, False),
        Pokemon('Pawmo', False, False, 0, False),
        Pokemon('Nacli', False, False, 0, False),
        Pokemon('Charcadet', False, False, 0, False),
        Pokemon('Tadbulb', False, False, 0, False),
        Pokemon('Toedscool', False, False, 0, False),
        Pokemon('Klawf', False, False, 0, False),
        Pokemon('Tinkatink', False, False, 0, False),
    ]
}
south_area_four = {
    'name': 'South Province (Area Four)',
    'key': 'south_area_four',
    'encounters': [
        Pokemon('Pikachu', False, False, 0, False),
        Pokemon('Persian', False, False, 0, False),
        Pokemon('Psyduck', False, False, 0, False),
        Pokemon('Primeape', False, False, 0, False),
        Pokemon('Arcanine', False, False, 0, False),
        Pokemon('Chansey', False, False, 0, False),
        Pokemon('Scyther', False, False, 0, False),
        Pokemon('Magikarp', False, False, 0, False),
        Pokemon('Flaaffy', False, False, 0, False),
        Pokemon('Marill', False, False, 0, False),
        Pokemon('Wooper', False, False, 0, False),
        Pokemon('Murkrow', False, False, 0, False),
        Pokemon('Misdreavus', False, True, 0, False),
        Pokemon('Pineco', False, False, 0, False),
        Pokemon('Dunsparce', False, False, 0, False),
        Pokemon('Houndour', False, False, 0, False),
        Pokemon('Houndoom', False, False, 0, False),
        Pokemon('Phanpy', False, False, 0, False),
        Pokemon('Donphan', False, False, 0, False),
        Pokemon('Meditite', False, False, 0, False),
        Pokemon('Grumpig', False, False, 0, False),
        Pokemon('Swablu', False, False, 0, False),
        Pokemon('Barboach', False, False, 0, False),
        Pokemon('Starly', False, False, 0, False),
        Pokemon('Staravia', False, False, 0, False),
        Pokemon('Combee', False, False, 0, False),
        Pokemon('Pachirisu', False, False, 0, False),
        Pokemon('Buizel', False, False, 0, False),
        Pokemon('Drifloon', True, False, 0, False),
        Pokemon('Bronzor', False, False, 0, False),
        Pokemon('Riolu', False, False, 0, False),
        Pokemon('Petilil', False, False, 0, False),
        Pokemon('Lilligant', False, False, 0, False),
        Pokemon('Basculin', False, False, 0, False),
        Pokemon('Deerling', False, False, 0, False),
        Pokemon('Sawsbuck', False, False, 0, False),
        Pokemon('Rufflet', False, False, 0, False),
        Pokemon('Fletchinder', False, False, 0, False),
        Pokemon('Spewpa', False, False, 0, False),
        Pokemon('Flabébé', False, False, 0, False),
        Pokemon('Floette', False, False, 0, False),
        Pokemon('Skiddo', False, False, 0, False),
        Pokemon('Hawlucha', False, False, 0, False),
        Pokemon('Goomy', False, False, 0, False),
        Pokemon('Yungoos', False, False, 0, False),
        Pokemon('Rockruff', False, False, 0, False),
        Pokemon('Salazzle', False, False, 0, False),
        Pokemon('Chewtle', False, False, 0, False),
        Pokemon('Toxel', False, False, 0, False),
        Pokemon('Hatenna', False, False, 0, False),
        Pokemon('Dreepy', False, True, 0, False),
        Pokemon('Lechonk', False, False, 0, False),
        Pokemon('Tarountula', False, False, 0, False),
        Pokemon('Pawmo', False, False, 0, False),
        Pokemon('Nacli', False, False, 0, False),
        Pokemon('Charcadet', False, False, 0, False),
        Pokemon('Tadbulb', False, False, 0, False),
        Pokemon('Bellibolt', False, False, 0, False),
        Pokemon('Maschiff', False, False, 0, False),
        Pokemon('Toedscool', False, False, 0, False),
        Pokemon('Flittle', False, False, 0, False)
    ]
}
south_area_five = {
    'name': 'South Province (Area Five)',
    'key': 'south_area_five',
    'encounters': [
        Pokemon('Psyduck', False, False, 0, False),
        Pokemon('Mankey', False, False, 0, False),
        Pokemon('Growlithe', False, False, 0, False),
        Pokemon('Slowpoke', False, False, 0, False),
        Pokemon('Drowzee', False, False, 0, False),
        Pokemon('Magikarp', False, False, 0, False),
        Pokemon('Eevee', False, False, 0, False),
        Pokemon('Marill', False, False, 0, False),
        Pokemon('Skiploom', False, False, 0, False),
        Pokemon('Wooper', False, False, 0, False),
        Pokemon('Murkrow', False, False, 0, False),
        Pokemon('Misdreavus', False, True, 0, False),
        Pokemon('Dunsparce', False, False, 0, False),
        Pokemon('Stantler', False, False, 0, False),
        Pokemon('Larvitar', True, False, 0, False),
        Pokemon('Surskit', False, False, 0, False),
        Pokemon('Masquerain', False, False, 0, False),
        Pokemon('Shroomish', False, False, 0, False),
        Pokemon('Slakoth', False, False, 0, False),
        Pokemon('Vigoroth', False, False, 0, False),
        Pokemon('Makuhita', False, False, 0, False),
        Pokemon('Hariyama', False, False, 0, False),
        Pokemon('Azurill', False, False, 0, False),
        Pokemon('Zangoose', False, False, 0, False),
        Pokemon('Seviper', False, False, 0, False),
        Pokemon('Barboach', False, False, 0, False),
        Pokemon('Staraptor', False, False, 0, False),
        Pokemon('Shinx', False, False, 0, False),
        Pokemon('Luxio', False, False, 0, False),
        Pokemon('Luxray', False, False, 0, False),
        Pokemon('Pachirisu', False, False, 0, False),
        Pokemon('Buizel', False, False, 0, False),
        Pokemon('Shellos', False, False, 0, False),
        Pokemon('Drifloon', True, False, 0, False),
        Pokemon('Stunky', True, False, 0, False),
        Pokemon('Bronzor', False, False, 0, False),
        Pokemon('Happiny', False, False, 0, False),
        Pokemon('Croagunk', False, False, 0, False),
        Pokemon('Basculin', False, False, 0, False),
        Pokemon('Deerling', False, False, 0, False),
        Pokemon('Axew', False, False, 0, False),
        Pokemon('Pawniard', False, False, 0, False),
        Pokemon('Fletchling', False, False, 0, False),
        Pokemon('Fletchinder', False, False, 0, False),
        Pokemon('Talonflame', False, False, 0, False),
        Pokemon('Scatterbug', False, False, 0, False),
        Pokemon('Litleo', False, False, 0, False),
        Pokemon('Skiddo', False, False, 0, False),
        Pokemon('Goomy', False, False, 0, False),
        Pokemon('Yungoos', False, False, 0, False),
        Pokemon('Gumshoos', False, False, 0, False),
        Pokemon('Crabrawler', False, False, 0, False),
        Pokemon('Mudbray', False, False, 0, False),
        Pokemon('Sandygast', False, False, 0, False),
        Pokemon('Rookidee', False, False, 0, False),
        Pokemon('Corvisquire', False, False, 0, False),
        Pokemon('Chewtle', False, False, 0, False),
        Pokemon('Drednaw', False, False, 0, False),
        Pokemon('Arrokuda', False, False, 0, False),
        Pokemon('Dreepy', False, True, 0, False),
        Pokemon('Lechonk', False, False, 0, False),
        Pokemon('Oinkologne', False, False, 0, False),
        Pokemon('Tarountula', False, False, 0, False),
        Pokemon('Pawmi', False, False, 0, False),
        Pokemon('Pawmo', False, False, 0, False),
        Pokemon('Nacli', False, False, 0, False),
        Pokemon('Naclstack', False, False, 0, False),
        Pokemon('Charcadet', False, False, 0, False),
        Pokemon('Tadbulb', False, False, 0, False),
        Pokemon('Toedscool', False, False, 0, False),
        Pokemon('Klawf', False, False, 0, False),
        Pokemon('Flittle', False, False, 0, False),
        Pokemon('Wiglett', False, False, 0, False),
    ]
}
south_area_six = {
    'name': 'South Province (Area Six)',
    'key': 'south_area_six',
    'encounters': [
        Pokemon('Psyduck', False, False, 0, False),
        Pokemon('Golduck', False, False, 0, False),
        Pokemon('Hypno', False, False, 0, False),
        Pokemon('Chansey', False, False, 0, False),
        Pokemon('Scyther', False, False, 0, False),
        Pokemon('Magikarp', False, False, 0, False),
        Pokemon('Vaporeon', False, False, 0, False),
        Pokemon('Flareon', False, False, 0, False),
        Pokemon('Dratini', False, False, 0, False),
        Pokemon('Sunflora', False, False, 0, False),
        Pokemon('Misdreavus', False, True, 0, False),
        Pokemon('Dunsparce', False, False, 0, False),
        Pokemon('Donphan', False, False, 0, False),
        Pokemon('Meditite', False, False, 0, False),
        Pokemon('Medicham', False, False, 0, False),
        Pokemon('Swablu', False, False, 0, False),
        Pokemon('Altaria', False, False, 0, False),
        Pokemon('Whiscash', False, False, 0, False),
        Pokemon('Vespiquen', False, False, 0, False),
        Pokemon('Drifloon', True, False, 0, False),
        Pokemon('Honchkrow', False, False, 0, False),
        Pokemon('Bronzong', False, False, 0, False),
        Pokemon('Lilligant', False, False, 0, False),
        Pokemon('Basculin', False, False, 0, False),
        Pokemon('Gothorita', False, False, 0, False),
        Pokemon('Gothitelle', False, False, 0, False),
        Pokemon('Rufflet', False, False, 0, False),
        Pokemon('Floette', False, False, 0, False),
        Pokemon('Gogoat', False, False, 0, False),
        Pokemon('Sylveon', False, False, 0, False),
        Pokemon('Klefki', False, False, 0, False),
        Pokemon('Gumshoos', False, False, 0, False),
        Pokemon('Mudsdale', False, False, 0, False),
        Pokemon('Greedent', False, False, 0, False),
        Pokemon('Drednaw', False, False, 0, False),
        Pokemon('Sinistea', False, False, 0, False),
        Pokemon('Sinistea', False, False, 0, False),
        Pokemon('Hattrem', False, False, 0, False),
        Pokemon('Dreepy', False, True, 0, False),
        Pokemon('Nymble', False, False, 0, False),
        Pokemon('Lokix', False, False, 0, False),
        Pokemon('Pawmo', False, False, 0, False),
        Pokemon('Bellibolt', False, False, 0, False),
        Pokemon('Scovillain', False, False, 0, False),
        Pokemon('Flittle', False, False, 0, False),
        Pokemon('Espathra', False, False, 0, False),
        Pokemon('Tinkatuff', False, False, 0, False),
    ]
}
# East Province
east_one = {
    'name': 'East Province (Area One)',
    'key': 'east_one',
    'encounters': [
        Pokemon('Pikachu', False, False, 0, False),
        Pokemon('Venonat', False, False, 0, False),
        Pokemon('Tauros', False, False, 0, False),
        Pokemon('Skiploom', False, False, 0, False),
        Pokemon('Murkrow', False, False, 0, False),
        Pokemon('Pineco', False, False, 0, False),
        Pokemon('Dunsparce', False, False, 0, False),
        Pokemon('Teddiursa', False, False, 0, False),
        Pokemon('Makuhita', False, False, 0, False),
        Pokemon('Azurill', False, False, 0, False),
        Pokemon('Gulpin', False, True, 0, False),
        Pokemon('Swablu', False, False, 0, False),
        Pokemon('Shuppet', False, False, 0, False),
        Pokemon('Shellos', False, False, 0, False),
        Pokemon('Deerling', False, False, 0, False),
        Pokemon('Fletchinder', False, False, 0, False),
        Pokemon('Litleo', False, False, 0, False),
        Pokemon('Skiddo', False, False, 0, False),
        Pokemon('Yungoos', False, False, 0, False),
        Pokemon('Gumshoos', False, False, 0, False),
        Pokemon('Oricorio', False, False, 0, False),
        Pokemon('Bounsweet', False, False, 0, False),
        Pokemon('Steenee', False, False, 0, False),
        Pokemon('Komala', False, False, 0, False),
        Pokemon('Rookidee', False, False, 0, False),
        Pokemon('Corvisquire', False, False, 0, False),
        Pokemon('Applin', False, False, 0, False),
        Pokemon('Lechonk', False, False, 0, False),
        Pokemon('Oinkologne', False, False, 0, False),
        Pokemon('Spidops', False, False, 0, False),
        Pokemon('Pawmo', False, False, 0, False),
        Pokemon('Tandemaus', False, False, 0, False),
        Pokemon('Squawkabilly', False, False, 0, False),
        Pokemon('Nacli', False, False, 0, False),
        Pokemon('Charcadet', False, False, 0, False),
        Pokemon('Tadbulb', False, False, 0, False),
        Pokemon('Wattrel', False, False, 0, False),
        Pokemon('Shroodle', False, False, 0, False),
        Pokemon('Toedscool', False, False, 0, False),
        Pokemon('Cyclizar', False, False, 0, False),
    ]
}
east_two = {
    'name': 'East Province (Area Two)',
    'key': 'east_two',
    'encounters': [
        Pokemon('Psyduck', False, False, 0, False),
        Pokemon('Slowpoke', False, False, 0, False),
        Pokemon('Magnemite', False, False, 0, False),
        Pokemon('Grimer', False, False, 0, False),
        Pokemon('Gastly', False, False, 0, False),
        Pokemon('Chansey', False, False, 0, False),
        Pokemon('Tauros', False, False, 0, False),
        Pokemon('Magikarp', False, False, 0, False),
        Pokemon('Marill', False, False, 0, False),
        Pokemon('Skiploom', False, False, 0, False),
        Pokemon('Murkrow', False, False, 0, False),
        Pokemon('Misdreavus', False, True, 0, False),
        Pokemon('Pineco', False, False, 0, False),
        Pokemon('Dunsparce', False, False, 0, False),
        Pokemon('Kirlia', False, False, 0, False),
        Pokemon('Makuhita', False, False, 0, False),
        Pokemon('Shuppet', False, False, 0, False),
        Pokemon('Pachirisu', False, False, 0, False),
        Pokemon('Buizel', False, False, 0, False),
        Pokemon('Drifloon', True, False, 0, False),
        Pokemon('Bronzor', False, False, 0, False),
        Pokemon('Rotom', False, False, 0, False),
        Pokemon('Basculin', False, False, 0, False),
        Pokemon('Deerling', False, False, 0, False),
        Pokemon('Litleo', False, False, 0, False),
        Pokemon('Skiddo', False, False, 0, False),
        Pokemon('Yungoos', False, False, 0, False),
        Pokemon('Gumshoos', False, False, 0, False),
        Pokemon('Crabrawler', False, False, 0, False),
        Pokemon('Crabominable', False, False, 0, False),
        Pokemon('Rockruff', False, False, 0, False),
        Pokemon('Mudbray', False, False, 0, False),
        Pokemon('Salandit', False, False, 0, False),
        Pokemon('Bounsweet', False, False, 0, False),
        Pokemon('Steenee', False, False, 0, False),
        Pokemon('Sandygast', False, False, 0, False),
        Pokemon('Komala', False, False, 0, False),
        Pokemon('Mimikyu', False, False, 0, False),
        Pokemon('Rookidee', False, False, 0, False),
        Pokemon('Corvisquire', False, False, 0, False),
        Pokemon('Chewtle', False, False, 0, False),
        Pokemon('Drednaw', False, False, 0, False),
        Pokemon('Applin', False, False, 0, False),
        Pokemon('Arrokuda', False, False, 0, False),
        Pokemon('Barraskewda', False, False, 0, False),
        Pokemon('Pincurchin', False, False, 0, False),
        Pokemon('Dreepy', False, True, 0, False),
        Pokemon('Lechonk', False, False, 0, False),
        Pokemon('Oinkologne', False, False, 0, False),
        Pokemon('Spidops', False, False, 0, False),
        Pokemon('Pawmo', False, False, 0, False),
        Pokemon('Tandemaus', False, False, 0, False),
        Pokemon('Squawkabilly', False, False, 0, False),
        Pokemon('Nacli', False, False, 0, False),
        Pokemon('Charcadet', False, False, 0, False),
        Pokemon('Tadbulb', False, False, 0, False),
        Pokemon('Wattrel', False, False, 0, False),
        Pokemon('Shroodle', False, False, 0, False),
        Pokemon('Toedscool', False, False, 0, False),
        Pokemon('Flittle', False, False, 0, False),
        Pokemon('Tinkatink', False, False, 0, False),
        Pokemon('Tinkatuff', False, False, 0, False),
        Pokemon('Wiglett', False, False, 0, False),
        Pokemon('Cyclizar', False, False, 0, False),
    ]
}
east_three = {
    'name': 'East Province (Area Three)',
    'key': 'east_three',
    'encounters': [
        Pokemon('Diglett', False, False, 0, False),
        Pokemon('Dugtrio', False, False, 0, False),
        Pokemon('Meowth', False, False, 0, False),
        Pokemon('Psyduck', False, False, 0, False),
        Pokemon('Growlithe', False, False, 0, False),
        Pokemon('Magnemite', False, False, 0, False),
        Pokemon('Gastly', False, False, 0, False),
        Pokemon('Voltorb', False, False, 0, False),
        Pokemon('Magikarp', False, False, 0, False),
        Pokemon('Murkrow', False, False, 0, False),
        Pokemon('Dunsparce', False, False, 0, False),
        Pokemon('Larvitar', True, False, 0, False),
        Pokemon('Makuhita', False, False, 0, False),
        Pokemon('Hariyama', False, False, 0, False),
        Pokemon('Sableye', False, False, 0, False),
        Pokemon('Torkoal', False, False, 0, False),
        Pokemon('Barboach', False, False, 0, False),
        Pokemon('Shuppet', False, False, 0, False),
        Pokemon('Bagon', False, True, 0, False),
        Pokemon('Buizel', False, False, 0, False),
        Pokemon('Basculin', False, False, 0, False),
        Pokemon('Gothita', False, False, 0, False),
        Pokemon('Pawniard', False, False, 0, False),
        Pokemon('Rufflet', False, False, 0, False),
        Pokemon('Skiddo', False, False, 0, False),
        Pokemon('Goomy', False, False, 0, False),
        Pokemon('Yungoos', False, False, 0, False),
        Pokemon('Gumshoos', False, False, 0, False),
        Pokemon('Salandit', False, False, 0, False),
        Pokemon('Rookidee', False, False, 0, False),
        Pokemon('Corvisquire', False, False, 0, False),
        Pokemon('Chewtle', False, False, 0, False),
        Pokemon('Drednaw', False, False, 0, False),
        Pokemon('Rolycoly', False, False, 0, False),
        Pokemon('Carkol', False, False, 0, False),
        Pokemon('Silicobra', False, False, 0, False),
        Pokemon('Arrokuda', False, False, 0, False),
        Pokemon('Barraskewda', False, False, 0, False),
        Pokemon('Sinistea', False, False, 0, False),
        Pokemon('Cufant', False, False, 0, False),
        Pokemon('Dreepy', False, True, 0, False),
        Pokemon('Lokix', False, False, 0, False),
        Pokemon('Tandemaus', False, False, 0, False),
        Pokemon('Squawkabilly', False, False, 0, False),
        Pokemon('Nacli', False, False, 0, False),
        Pokemon('Charcadet', False, False, 0, False),
        Pokemon('Tadbulb', False, False, 0, False),
        Pokemon('Bellibolt', False, False, 0, False),
        Pokemon('Bramblin', False, False, 0, False),
        Pokemon('Varoom', False, False, 0, False),
        Pokemon('Orthworm', False, False, 0, False),
        Pokemon('Glimmet', False, False, 0, False),
        Pokemon('Flamigo', False, False, 0, False)
    ]
}
# North Province
north_one = {
    'name': 'North Province (Area One)',
    'key': 'north_one',
    'encounters': [
        Pokemon('Wigglytuff', False, False, 0, False),
        Pokemon('Golduck', False, False, 0, False),
        Pokemon('Primeape', False, False, 0, False),
        Pokemon('Haunter', False, False, 0, False),
        Pokemon('Chansey', False, False, 0, False),
        Pokemon('Magikarp', False, False, 0, False),
        Pokemon('Flareon', False, False, 0, False),
        Pokemon('Ampharos', False, False, 0, False),
        Pokemon('Jumpluff', False, False, 0, False),
        Pokemon('Umbreon', False, False, 0, False),
        Pokemon('Ursaring', False, False, 0, False),
        Pokemon('Blissey', False, False, 0, False),
        Pokemon('Vigoroth', False, False, 0, False),
        Pokemon('Sableye', False, False, 0, False),
        Pokemon('Grumpig', False, False, 0, False),
        Pokemon('Altaria', False, False, 0, False),
        Pokemon('Whiscash', False, False, 0, False),
        Pokemon('Vespiquen', False, False, 0, False),
        Pokemon('Gastrodon', False, False, 0, False),
        Pokemon('Drifblim', True, False, 0, False),
        Pokemon('Mismagius', False, True, 0, False),
        Pokemon('Honchkrow', False, False, 0, False),
        Pokemon('Spiritomb', False, False, 0, False),
        Pokemon('Riolu', False, False, 0, False),
        Pokemon('Lucario', False, False, 0, False),
        Pokemon('Gallade', False, False, 0, False),
        Pokemon('Sawsbuck', False, False, 0, False),
        Pokemon('Eelektross', False, False, 0, False),
        Pokemon('Axew', False, False, 0, False),
        Pokemon('Fraxure', False, False, 0, False),
        Pokemon('Rufflet', False, False, 0, False),
        Pokemon('Braviary', False, False, 0, False),
        Pokemon('Vivillon', False, False, 0, False),
        Pokemon('Pyroar', False, False, 0, False),
        Pokemon('Floette', False, False, 0, False),
        Pokemon('Gogoat', False, False, 0, False),
        Pokemon('Hawlucha', False, False, 0, False),
        Pokemon('Noibat', False, False, 0, False),
        Pokemon('Noivern', False, False, 0, False),
        Pokemon('Gumshoos', False, False, 0, False),
        Pokemon('Lycanroc', False, False, 0, False),
        Pokemon('Mudsdale', False, False, 0, False),
        Pokemon('Lurantis', False, False, 0, False),
        Pokemon('Salazzle', False, False, 0, False),
        Pokemon('Greedent', False, False, 0, False),
        Pokemon('Barraskewda', False, False, 0, False),
        Pokemon('Pincurchin', False, False, 0, False),
        Pokemon('Frosmoth', False, False, 0, False),
        Pokemon('Indeedee', False, False, 0, False),
        Pokemon('Copperajah', False, False, 0, False),
        Pokemon('Drakloak', False, True, 0, False),
        Pokemon('Lokix', False, False, 0, False),
        Pokemon('Pawmo', False, False, 0, False),
        Pokemon('Naclstack', False, False, 0, False),
        Pokemon('Kilowattrel', False, False, 0, False),
        Pokemon('Brambleghast', False, False, 0, False),
        Pokemon('Scovillain', False, False, 0, False),
        Pokemon('Flittle', False, False, 0, False),
        Pokemon('Espathra', False, False, 0, False),
        Pokemon('Tinkatuff', False, False, 0, False),
        Pokemon('Wiglett', False, False, 0, False),
        Pokemon('Wugtrio', False, False, 0, False),
        Pokemon('Revavroom', False, False, 0, False),
        Pokemon('Glimmet', False, False, 0, False),
        Pokemon('Houndstone', False, False, 0, False)
    ]
}
north_two = {
    'name': 'North Province (Area Two)',
    'key': 'north_two',
    'encounters': [
        Pokemon('Venomoth', False, False, 0, False),
        Pokemon('Dugtrio', False, False, 0, False),
        Pokemon('Growlithe', False, False, 0, False),
        Pokemon('Arcanine', False, False, 0, False),
        Pokemon('Chansey', False, False, 0, False),
        Pokemon('Scyther', False, False, 0, False),
        Pokemon('Vaporeon', False, False, 0, False),
        Pokemon('Dratini', False, False, 0, False),
        Pokemon('Dragonite', False, False, 0, False),
        Pokemon('Jumpluff', False, False, 0, False),
        Pokemon('Sunflora', False, False, 0, False),
        Pokemon('Umbreon', False, False, 0, False),
        Pokemon('Heracross', False, False, 0, False),
        Pokemon('Teddiursa', False, False, 0, False),
        Pokemon('Ursaring', False, False, 0, False),
        Pokemon('Houndoom', False, False, 0, False),
        Pokemon('Blissey', False, False, 0, False),
        Pokemon('Slaking', False, False, 0, False),
        Pokemon('Camerupt', False, False, 0, False),
        Pokemon('Grumpig', False, False, 0, False),
        Pokemon('Altaria', False, False, 0, False),
        Pokemon('Shelgon', False, True, 0, False),
        Pokemon('Kricketune', False, False, 0, False),
        Pokemon('Luxray', False, False, 0, False),
        Pokemon('Vespiquen', False, False, 0, False),
        Pokemon('Mismagius', False, True, 0, False),
        Pokemon('Honchkrow', False, False, 0, False),
        Pokemon('Bronzong', False, False, 0, False),
        Pokemon('Gabite', False, False, 0, False),
        Pokemon('Lucario', False, False, 0, False),
        Pokemon('Foongus', False, False, 0, False),
        Pokemon('Amoonguss', False, False, 0, False),
        Pokemon('Pawniard', False, False, 0, False),
        Pokemon('Bisharp', False, False, 0, False),
        Pokemon('Rufflet', False, False, 0, False),
        Pokemon('Deino', True, False, 0, False),
        Pokemon('Zweilous', True, False, 0, False),
        Pokemon('Vivillon', False, False, 0, False),
        Pokemon('Floette', False, False, 0, False),
        Pokemon('Gogoat', False, False, 0, False),
        Pokemon('Hawlucha', False, False, 0, False),
        Pokemon('Noibat', False, False, 0, False),
        Pokemon('Noivern', False, False, 0, False),
        Pokemon('Lurantis', False, False, 0, False),
        Pokemon('Salazzle', False, False, 0, False),
        Pokemon('Oranguru', True, False, 0, False),
        Pokemon('Passimian', False, True, 0, False),
        Pokemon('Falinks', False, False, 0, False),
        Pokemon('Copperajah', False, False, 0, False),
        Pokemon('Drakloak', False, True, 0, False),
        Pokemon('Spidops', False, False, 0, False),
        Pokemon('Lokix', False, False, 0, False),
        Pokemon('Naclstack', False, False, 0, False),
        Pokemon('Mabosstiff', False, False, 0, False),
        Pokemon('Grafaiai', False, False, 0, False),
        Pokemon('Revavroom', False, False, 0, False),
    ]
}
north_three = {
    'name': 'North Province (Area Three)',
    'key': 'north_three',
    'encounters': [
        Pokemon('Dugtrio', False, False, 0, False),
        Pokemon('Golduck', False, False, 0, False),
        Pokemon('Hypno', False, False, 0, False),
        Pokemon('Chansey', False, False, 0, False),
        Pokemon('Vaporeon', False, False, 0, False),
        Pokemon('Jumpluff', False, False, 0, False),
        Pokemon('Sunflora', False, False, 0, False),
        Pokemon('Espeon', False, False, 0, False),
        Pokemon('Umbreon', False, False, 0, False),
        Pokemon('Blissey', False, False, 0, False),
        Pokemon('Wingull', False, False, 0, False),
        Pokemon('Vespiquen', False, False, 0, False),
        Pokemon('Gastrodon', False, False, 0, False),
        Pokemon('Honchkrow', False, False, 0, False),
        Pokemon('Lilligant', False, False, 0, False),
        Pokemon('Vivillon', False, False, 0, False),
        Pokemon('Floette', False, False, 0, False),
        Pokemon('Florges', False, False, 0, False),
        Pokemon('Florges', False, False, 0, False),
        Pokemon('Gogoat', False, False, 0, False),
        Pokemon('Hawlucha', False, False, 0, False),
        Pokemon('Dedenne', False, False, 0, False),
        Pokemon('Lurantis', False, False, 0, False),
        Pokemon('Salazzle', False, False, 0, False),
        Pokemon('Barraskewda', False, False, 0, False),
        Pokemon('Pincurchin', False, False, 0, False),
        Pokemon('Eiscue', False, True, 0, False),
        Pokemon('Copperajah', False, False, 0, False),
        Pokemon('Drakloak', False, True, 0, False),
        Pokemon('Lokix', False, False, 0, False),
        Pokemon('Pawmo', False, False, 0, False),
        Pokemon('Dolliv', False, False, 0, False),
        Pokemon('Naclstack', False, False, 0, False),
        Pokemon('Bellibolt', False, False, 0, False),
        Pokemon('Scovillain', False, False, 0, False),
        Pokemon('Tinkatuff', False, False, 0, False),
        Pokemon('Wugtrio', False, False, 0, False)
    ]
}
# West Province
west_one = {
    'name': 'West Province (Area One)',
    'key': 'west_one',
    'encounters': [
        Pokemon('Psyduck', False, False, 0, False),
        Pokemon('Mankey', False, False, 0, False),
        Pokemon('Primeape', False, False, 0, False),
        Pokemon('Gastly', False, False, 0, False),
        Pokemon('Haunter', False, False, 0, False),
        Pokemon('Hypno', False, False, 0, False),
        Pokemon('Voltorb', False, False, 0, False),
        Pokemon('Marill', False, False, 0, False),
        Pokemon('Misdreavus', False, True, 0, False),
        Pokemon('Phanpy', False, False, 0, False),
        Pokemon('Larvitar', True, False, 0, False),
        Pokemon('Makuhita', False, False, 0, False),
        Pokemon('Sableye', False, False, 0, False),
        Pokemon('Swablu', False, False, 0, False),
        Pokemon('Combee', False, False, 0, False),
        Pokemon('Vespiquen', False, False, 0, False),
        Pokemon('Buizel', False, False, 0, False),
        Pokemon('Drifloon', True, False, 0, False),
        Pokemon('Bronzor', False, False, 0, False),
        Pokemon('Happiny', False, False, 0, False),
        Pokemon('Gible', False, False, 0, False),
        Pokemon('Petilil', False, False, 0, False),
        Pokemon('Basculin', False, False, 0, False),
        Pokemon('Flabébé', False, False, 0, False),
        Pokemon('Floette', False, False, 0, False),
        Pokemon('Skiddo', False, False, 0, False),
        Pokemon('Yungoos', False, False, 0, False),
        Pokemon('Gumshoos', False, False, 0, False),
        Pokemon('Crabrawler', False, False, 0, False),
        Pokemon('Rockruff', False, False, 0, False),
        Pokemon('Mudbray', False, False, 0, False),
        Pokemon('Salandit', False, False, 0, False),
        Pokemon('Chewtle', False, False, 0, False),
        Pokemon('Arrokuda', False, False, 0, False),
        Pokemon('Falinks', False, False, 0, False),
        Pokemon('Nymble', False, False, 0, False),
        Pokemon('Pawmi', False, False, 0, False),
        Pokemon('Pawmo', False, False, 0, False),
        Pokemon('Squawkabilly', False, False, 0, False),
        Pokemon('Nacli', False, False, 0, False),
        Pokemon('Charcadet', False, False, 0, False),
        Pokemon('Wattrel', False, False, 0, False),
        Pokemon('Capsakid', False, False, 0, False),
        Pokemon('Flittle', False, False, 0, False),
        Pokemon('Tinkatink', False, False, 0, False),
        Pokemon('Wiglett', False, False, 0, False),
        Pokemon('Bombirdier', False, False, 0, False),
    ]
}
west_two = {
    'name': 'West Province (Area Two)',
    'key': 'west_two',
    'encounters': [
        Pokemon('Psyduck', False, False, 0, False),
        Pokemon('Slowpoke', False, False, 0, False),
        Pokemon('Slowbro', False, False, 0, False),
        Pokemon('Chansey', False, False, 0, False),
        Pokemon('Tauros', False, False, 0, False),
        Pokemon('Magikarp', False, False, 0, False),
        Pokemon('Ditto', False, False, 0, False),
        Pokemon('Jolteon', False, False, 0, False),
        Pokemon('Flaaffy', False, False, 0, False),
        Pokemon('Azumarill', False, False, 0, False),
        Pokemon('Skiploom', False, False, 0, False),
        Pokemon('Murkrow', False, False, 0, False),
        Pokemon('Girafarig', False, False, 0, False),
        Pokemon('Dunsparce', False, False, 0, False),
        Pokemon('Donphan', False, False, 0, False),
        Pokemon('Hariyama', False, False, 0, False),
        Pokemon('Sableye', False, False, 0, False),
        Pokemon('Meditite', False, False, 0, False),
        Pokemon('Barboach', False, False, 0, False),
        Pokemon('Tropius', False, False, 0, False),
        Pokemon('Bagon', False, True, 0, False),
        Pokemon('Staravia', False, False, 0, False),
        Pokemon('Buizel', False, False, 0, False),
        Pokemon('Floatzel', False, False, 0, False),
        Pokemon('Stunky', True, False, 0, False),
        Pokemon('Bronzor', False, False, 0, False),
        Pokemon('Gible', False, False, 0, False),
        Pokemon('Gabite', False, False, 0, False),
        Pokemon('Croagunk', False, False, 0, False),
        Pokemon('Rotom', False, False, 0, False),
        Pokemon('Basculin', False, False, 0, False),
        Pokemon('Deerling', False, False, 0, False),
        Pokemon('Fletchinder', False, False, 0, False),
        Pokemon('Skiddo', False, False, 0, False),
        Pokemon('Noibat', False, False, 0, False),
        Pokemon('Yungoos', False, False, 0, False),
        Pokemon('Gumshoos', False, False, 0, False),
        Pokemon('Crabrawler', False, False, 0, False),
        Pokemon('Salandit', False, False, 0, False),
        Pokemon('Sandygast', False, False, 0, False),
        Pokemon('Palossand', False, False, 0, False),
        Pokemon('Chewtle', False, False, 0, False),
        Pokemon('Drednaw', False, False, 0, False),
        Pokemon('Arrokuda', False, False, 0, False),
        Pokemon('Barraskewda', False, False, 0, False),
        Pokemon('Falinks', False, False, 0, False),
        Pokemon('Pincurchin', False, False, 0, False),
        Pokemon('Dreepy', False, True, 0, False),
        Pokemon('Oinkologne', False, False, 0, False),
        Pokemon('Lokix', False, False, 0, False),
        Pokemon('Pawmo', False, False, 0, False),
        Pokemon('Tandemaus', False, False, 0, False),
        Pokemon('Nacli', False, False, 0, False),
        Pokemon('Charcadet', False, False, 0, False),
        Pokemon('Tadbulb', False, False, 0, False),
        Pokemon('Bellibolt', False, False, 0, False),
        Pokemon('Wattrel', False, False, 0, False),
        Pokemon('Maschiff', False, False, 0, False),
        Pokemon('Toedscool', False, False, 0, False),
        Pokemon('Tinkatuff', False, False, 0, False),
        Pokemon('Wiglett', False, False, 0, False),
        Pokemon('Wugtrio', False, False, 0, False),
        Pokemon('Finizen', False, False, 0, False),
        Pokemon('Cyclizar', False, False, 0, False),
        Pokemon('Glimmet', False, False, 0, False),
    ]
}
# Sea
west_paldean_sea = {
    'name': 'West Paldean Sea',
    'key': 'west_paldean_sea',
    'encounters': [
        Pokemon('Shellder', False, False, 0, False),
        Pokemon('Cloyster', False, False, 0, False),
        Pokemon('Magikarp', False, False, 0, False),
        Pokemon('Gyarados', False, False, 0, False),
        Pokemon('Qwilfish', False, False, 0, False),
        Pokemon('Wingull', False, False, 0, False),
        Pokemon('Pelipper', False, False, 0, False),
        Pokemon('Luvdisc', False, False, 0, False),
        Pokemon('Buizel', False, False, 0, False),
        Pokemon('Floatzel', False, False, 0, False),
        Pokemon('Finneon', False, False, 0, False),
        Pokemon('Lumineon', False, False, 0, False),
        Pokemon('Tynamo', False, False, 0, False),
        Pokemon('Eelektrik', False, False, 0, False),
        Pokemon('Skrelp', True, False, 0, False),
        Pokemon('Clauncher', False, True, 0, False),
        Pokemon('Bruxish', False, False, 0, False),
        Pokemon('Arrokuda', False, False, 0, False),
        Pokemon('Barraskewda', False, False, 0, False),
        Pokemon('Wattrel', False, False, 0, False),
        Pokemon('Kilowattrel', False, False, 0, False),
        Pokemon('Bombirdier', False, False, 0, False),
        Pokemon('Finizen', False, False, 0, False),
    ]
}
south_paldean_sea = {
    'name': 'South Paldean Sea',
    'key': 'south_paldean_sea',
    'encounters': [
        Pokemon('Shellder', False, False, 0, False),
        Pokemon('Cloyster', False, False, 0, False),
        Pokemon('Magikarp', False, False, 0, False),
        Pokemon('Gyarados', False, False, 0, False),
        Pokemon('Qwilfish', False, False, 0, False),
        Pokemon('Wingull', False, False, 0, False),
        Pokemon('Luvdisc', False, False, 0, False),
        Pokemon('Buizel', False, False, 0, False),
        Pokemon('Floatzel', False, False, 0, False),
        Pokemon('Eelektrik', False, False, 0, False),
        Pokemon('Skrelp', True, False, 0, False),
        Pokemon('Clauncher', False, True, 0, False),
        Pokemon('Clawitzer', False, True, 0, False),
        Pokemon('Arrokuda', False, False, 0, False),
        Pokemon('Barraskewda', False, False, 0, False),
        Pokemon('Wattrel', False, False, 0, False)
    ]
}
east_paldean_sea = {
    'name': 'East Paldean Sea',
    'key': 'east_paldean_sea',
    'encounters': [
        Pokemon('Shellder', False, False, 0, False),
        Pokemon('Cloyster', False, False, 0, False),
        Pokemon('Magikarp', False, False, 0, False),
        Pokemon('Gyarados', False, False, 0, False),
        Pokemon('Sunflora', False, False, 0, False),
        Pokemon('Qwilfish', False, False, 0, False),
        Pokemon('Luvdisc', False, False, 0, False),
        Pokemon('Combee', False, False, 0, False),
        Pokemon('Vespiquen', False, False, 0, False),
        Pokemon('Buizel', False, False, 0, False),
        Pokemon('Floatzel', False, False, 0, False),
        Pokemon('Vivillon', False, False, 0, False),
        Pokemon('Flabébé', False, False, 0, False),
        Pokemon('Floette', False, False, 0, False),
        Pokemon('Skrelp', True, False, 0, False),
        Pokemon('Clauncher', False, True, 0, False),
        Pokemon('Mareanie', False, False, 0, False),
        Pokemon('Toxapex', False, False, 0, False),
        Pokemon('Bruxish', False, False, 0, False),
        Pokemon('Arrokuda', False, False, 0, False),
        Pokemon('Barraskewda', False, False, 0, False),
        Pokemon('Dolliv', False, False, 0, False),
        Pokemon('Wattrel', False, False, 0, False),
        Pokemon('Kilowattrel', False, False, 0, False)
    ]
}
north_paldean_sea = {
    'name': 'North Paldean Sea',
    'key': 'north_paldean_sea',
    'encounters': [
        Pokemon('Shellder', False, False, 0, False),
        Pokemon('Cloyster', False, False, 0, False),
        Pokemon('Magikarp', False, False, 0, False),
        Pokemon('Gyarados', False, False, 0, False),
        Pokemon('Qwilfish', False, False, 0, False),
        Pokemon('Pelipper', False, False, 0, False),
        Pokemon('Floatzel', False, False, 0, False),
        Pokemon('Lumineon', False, False, 0, False),
        Pokemon('Alomomola', False, False, 0, False),
        Pokemon('Tynamo', False, False, 0, False),
        Pokemon('Eelektrik', False, False, 0, False),
        Pokemon('Skrelp', True, False, 0, False),
        Pokemon('Dragalge', True, False, 0, False),
        Pokemon('Clauncher', False, True, 0, False),
        Pokemon('Clawitzer', False, True, 0, False),
        Pokemon('Bergmite', False, False, 0, False),
        Pokemon('Avalugg', False, False, 0, False),
        Pokemon('Barraskewda', False, False, 0, False),
        Pokemon('Eiscue', False, True, 0, False),
        Pokemon('Kilowattrel', False, False, 0, False),
        Pokemon('Finizen', False, False, 0, False),
    ]
}
# Other areas
asado_desert = {
    'name': 'Asado Desert',
    'key': 'asado_desert',
    'encounters': [
        Pokemon('Diglett', False, False, 0, False),
        Pokemon('Dugtrio', False, False, 0, False),
        Pokemon('Dunsparce', False, False, 0, False),
        Pokemon('Phanpy', False, False, 0, False),
        Pokemon('Donphan', False, False, 0, False),
        Pokemon('Larvitar', True, False, 0, False),
        Pokemon('Makuhita', False, False, 0, False),
        Pokemon('Numel', False, False, 0, False),
        Pokemon('Cacnea', False, False, 0, False),
        Pokemon('Hippopotas', False, False, 0, False),
        Pokemon('Sandile', False, False, 0, False),
        Pokemon('Rufflet', False, False, 0, False),
        Pokemon('Braviary', False, False, 0, False),
        Pokemon('Larvesta', False, False, 0, False),
        Pokemon('Skiddo', False, False, 0, False),
        Pokemon('Yungoos', False, False, 0, False),
        Pokemon('Gumshoos', False, False, 0, False),
        Pokemon('Silicobra', False, False, 0, False),
        Pokemon('Stonjourner', True, False, 0, False),
        Pokemon('Lokix', False, False, 0, False),
        Pokemon('Nacli', False, False, 0, False),
        Pokemon('Charcadet', False, False, 0, False),
        Pokemon('Bramblin', False, False, 0, False),
        Pokemon('Capsakid', False, False, 0, False),
        Pokemon('Rellor', False, False, 0, False),
        Pokemon('Flittle', False, False, 0, False),
        Pokemon('Espathra', False, False, 0, False),
        Pokemon('Tinkatink', False, False, 0, False),
        Pokemon('Orthworm', False, False, 0, False)
    ]
}
alfornada_cavern = {
    'name': 'Alfornada Cavern',
    'key': 'alfornada_cavern',
    'encounters': [
        Pokemon('Diglett', False, False, 0, False),
        Pokemon('Dugtrio', False, False, 0, False),
        Pokemon('Ampharos', False, False, 0, False),
        Pokemon('Umbreon', False, False, 0, False),
        Pokemon('Dunsparce', False, False, 0, False),
        Pokemon('Larvitar', True, False, 0, False),
        Pokemon('Pupitar', True, False, 0, False),
        Pokemon('Hariyama', False, False, 0, False),
        Pokemon('Sableye', False, False, 0, False),
        Pokemon('Meditite', False, False, 0, False),
        Pokemon('Medicham', False, False, 0, False),
        Pokemon('Altaria', False, False, 0, False),
        Pokemon('Banette', False, False, 0, False),
        Pokemon('Bagon', False, True, 0, False),
        Pokemon('Shelgon', False, True, 0, False),
        Pokemon('Drifblim', True, False, 0, False),
        Pokemon('Mismagius', False, True, 0, False),
        Pokemon('Gible', False, False, 0, False),
        Pokemon('Gabite', False, False, 0, False),
        Pokemon('Gallade', False, False, 0, False),
        Pokemon('Deino', True, False, 0, False),
        Pokemon('Gumshoos', False, False, 0, False),
        Pokemon('Lycanroc', False, False, 0, False),
        Pokemon('Lycanroc', False, False, 0, False),
        Pokemon('Mudbray', False, False, 0, False),
        Pokemon('Mudsdale', False, False, 0, False),
        Pokemon('Salandit', False, False, 0, False),
        Pokemon('Salazzle', False, False, 0, False),
        Pokemon('Toxtricity', False, False, 0, False),
        Pokemon('Lokix', False, False, 0, False),
        Pokemon('Naclstack', False, False, 0, False)
    ]
}
casseroya_lake = {
    'name': 'Casseroya Lake',
    'key': 'casseroya_lake',
    'encounters': [
        Pokemon('Venomoth', False, False, 0, False),
        Pokemon('Psyduck', False, False, 0, False),
        Pokemon('Golduck', False, False, 0, False),
        Pokemon('Slowpoke', False, False, 0, False),
        Pokemon('Slowbro', False, False, 0, False),
        Pokemon('Chansey', False, False, 0, False),
        Pokemon('Scyther', False, False, 0, False),
        Pokemon('Gyarados', False, False, 0, False),
        Pokemon('Vaporeon', False, False, 0, False),
        Pokemon('Dratini', False, False, 0, False),
        Pokemon('Dragonair', False, False, 0, False),
        Pokemon('Dragonite', False, False, 0, False),
        Pokemon('Azumarill', False, False, 0, False),
        Pokemon('Forretress', False, False, 0, False),
        Pokemon('Swalot', False, True, 0, False),
        Pokemon('Swablu', False, False, 0, False),
        Pokemon('Altaria', False, False, 0, False),
        Pokemon('Tropius', False, False, 0, False),
        Pokemon('Staraptor', False, False, 0, False),
        Pokemon('Gastrodon', False, False, 0, False),
        Pokemon('Mismagius', False, True, 0, False),
        Pokemon('Honchkrow', False, False, 0, False),
        Pokemon('Skuntank', True, False, 0, False),
        Pokemon('Bronzong', False, False, 0, False),
        Pokemon('Spiritomb', False, False, 0, False),
        Pokemon('Toxicroak', False, False, 0, False),
        Pokemon('Gogoat', False, False, 0, False),
        Pokemon('Hawlucha', False, False, 0, False),
        Pokemon('Sliggoo', False, False, 0, False),
        Pokemon('Bergmite', False, False, 0, False),
        Pokemon('Avalugg', False, False, 0, False),
        Pokemon('Tsareena', False, False, 0, False),
        Pokemon('Drednaw', False, False, 0, False),
        Pokemon('Copperajah', False, False, 0, False),
        Pokemon('Drakloak', False, True, 0, False),
        Pokemon('Lokix', False, False, 0, False),
        Pokemon('Naclstack', False, False, 0, False),
        Pokemon('Kilowattrel', False, False, 0, False),
        Pokemon('Houndstone', False, False, 0, False),
        Pokemon('Flamigo', False, False, 0, False),
        Pokemon('Veluza', False, False, 0, False),
        Pokemon('Dondozo', False, False, 0, False),
        Pokemon('Tatsugiri', False, False, 0, False)
    ]
}
socarrat_trail = {
    'name': 'Socarrat Trail',
    'key': 'socarrat_trail',
    'encounters': [
        Pokemon('Raichu', False, False, 0, False),
        Pokemon('Jolteon', False, False, 0, False),
        Pokemon('Sudowoodo', False, False, 0, False),
        Pokemon('Forretress', False, False, 0, False),
        Pokemon('Heracross', False, False, 0, False),
        Pokemon('Slaking', False, False, 0, False),
        Pokemon('Honchkrow', False, False, 0, False),
        Pokemon('Spiritomb', False, False, 0, False),
        Pokemon('Leafeon', False, False, 0, False),
        Pokemon('Zoroark', False, False, 0, False),
        Pokemon('Sawsbuck', False, False, 0, False),
        Pokemon('Amoonguss', False, False, 0, False),
        Pokemon('Hawlucha', False, False, 0, False),
        Pokemon('Fomantis', False, False, 0, False),
        Pokemon('Lurantis', False, False, 0, False),
        Pokemon('Spidops', False, False, 0, False),
        Pokemon('Grafaiai', False, False, 0, False),
        Pokemon('Brambleghast', False, False, 0, False),
        Pokemon('Toedscool', False, False, 0, False),
        Pokemon('Toedscruel', False, False, 0, False)
    ]
}
tagtree_thicket = {
    'name': 'Tagtree Thicket',
    'key': 'tagtree_thicket',
    'encounters': [
        Pokemon('Venonat', False, False, 0, False),
        Pokemon('Venomoth', False, False, 0, False),
        Pokemon('Psyduck', False, False, 0, False),
        Pokemon('Magikarp', False, False, 0, False),
        Pokemon('Vaporeon', False, False, 0, False),
        Pokemon('Sunflora', False, False, 0, False),
        Pokemon('Murkrow', False, False, 0, False),
        Pokemon('Misdreavus', False, True, 0, False),
        Pokemon('Pineco', False, False, 0, False),
        Pokemon('Dunsparce', False, False, 0, False),
        Pokemon('Barboach', False, False, 0, False),
        Pokemon('Whiscash', False, False, 0, False),
        Pokemon('Combee', False, False, 0, False),
        Pokemon('Buizel', False, False, 0, False),
        Pokemon('Drifloon', True, False, 0, False),
        Pokemon('Zorua', False, False, 0, False),
        Pokemon('Foongus', False, False, 0, False),
        Pokemon('Gumshoos', False, False, 0, False),
        Pokemon('Fomantis', False, False, 0, False),
        Pokemon('Oranguru', True, False, 0, False),
        Pokemon('Passimian', False, True, 0, False),
        Pokemon('Komala', False, False, 0, False),
        Pokemon('Mimikyu', False, False, 0, False),
        Pokemon('Greedent', False, False, 0, False),
        Pokemon('Applin', False, False, 0, False),
        Pokemon('Hattrem', False, False, 0, False),
        Pokemon('Impidimp', False, False, 0, False),
        Pokemon('Morgrem', False, False, 0, False),
        Pokemon('Oinkologne', False, False, 0, False),
        Pokemon('Spidops', False, False, 0, False),
        Pokemon('Dolliv', False, False, 0, False),
        Pokemon('Charcadet', False, False, 0, False),
        Pokemon('Bellibolt', False, False, 0, False),
        Pokemon('Shroodle', False, False, 0, False),
        Pokemon('Grafaiai', False, False, 0, False)
    ]
}
dalizapa_passage = {
    'name': 'Dalizapa Passage',
    'key': 'dalizapa_passage',
    'encounters': [
        Pokemon('Dugtrio', False, False, 0, False),
        Pokemon('Magneton', False, False, 0, False),
        Pokemon('Haunter', False, False, 0, False),
        Pokemon('Hypno', False, False, 0, False),
        Pokemon('Magikarp', False, False, 0, False),
        Pokemon('Flareon', False, False, 0, False),
        Pokemon('Umbreon', False, False, 0, False),
        Pokemon('Misdreavus', False, True, 0, False),
        Pokemon('Dunsparce', False, False, 0, False),
        Pokemon('Sneasel', False, False, 0, False),
        Pokemon('Ursaring', False, False, 0, False),
        Pokemon('Phanpy', False, False, 0, False),
        Pokemon('Donphan', False, False, 0, False),
        Pokemon('Larvitar', True, False, 0, False),
        Pokemon('Kirlia', False, False, 0, False),
        Pokemon('Vigoroth', False, False, 0, False),
        Pokemon('Hariyama', False, False, 0, False),
        Pokemon('Sableye', False, False, 0, False),
        Pokemon('Medicham', False, False, 0, False),
        Pokemon('Torkoal', False, False, 0, False),
        Pokemon('Grumpig', False, False, 0, False),
        Pokemon('Snorunt', False, False, 0, False),
        Pokemon('Bagon', False, True, 0, False),
        Pokemon('Drifloon', True, False, 0, False),
        Pokemon('Drifblim', True, False, 0, False),
        Pokemon('Honchkrow', False, False, 0, False),
        Pokemon('Bronzong', False, False, 0, False),
        Pokemon('Spiritomb', False, False, 0, False),
        Pokemon('Gabite', False, False, 0, False),
        Pokemon('Weavile', False, False, 0, False),
        Pokemon('Gallade', False, False, 0, False),
        Pokemon('Froslass', False, False, 0, False),
        Pokemon('Deerling', False, False, 0, False),
        Pokemon('Sawsbuck', False, False, 0, False),
        Pokemon('Axew', False, False, 0, False),
        Pokemon('Fraxure', False, False, 0, False),
        Pokemon('Cubchoo', False, False, 0, False),
        Pokemon('Beartic', False, False, 0, False),
        Pokemon('Rufflet', False, False, 0, False),
        Pokemon('Deino', True, False, 0, False),
        Pokemon('Pyroar', False, False, 0, False),
        Pokemon('Gogoat', False, False, 0, False),
        Pokemon('Gumshoos', False, False, 0, False),
        Pokemon('Lycanroc', False, False, 0, False),
        Pokemon('Lycanroc', False, False, 0, False),
        Pokemon('Mudbray', False, False, 0, False),
        Pokemon('Mudsdale', False, False, 0, False),
        Pokemon('Salandit', False, False, 0, False),
        Pokemon('Salazzle', False, False, 0, False),
        Pokemon('Greedent', False, False, 0, False),
        Pokemon('Snom', False, False, 0, False),
        Pokemon('Copperajah', False, False, 0, False),
        Pokemon('Lokix', False, False, 0, False),
        Pokemon('Naclstack', False, False, 0, False),
        Pokemon('Scovillain', False, False, 0, False),
        Pokemon('Flittle', False, False, 0, False),
        Pokemon('Espathra', False, False, 0, False),
        Pokemon('Tinkatuff', False, False, 0, False),
        Pokemon('Revavroom', False, False, 0, False),
        Pokemon('Cyclizar', False, False, 0, False),
        Pokemon('Greavard', False, False, 0, False),
        Pokemon('Houndstone', False, False, 0, False),
    ]
}
glaseado_mountain = {
    'name': 'Glaseado Mountain',
    'key': 'glaseado_mountain',
    'encounters': [
        Pokemon('Psyduck', False, False, 0, False),
        Pokemon('Golduck', False, False, 0, False),
        Pokemon('Magneton', False, False, 0, False),
        Pokemon('Haunter', False, False, 0, False),
        Pokemon('Vaporeon', False, False, 0, False),
        Pokemon('Misdreavus', False, True, 0, False),
        Pokemon('Sneasel', False, False, 0, False),
        Pokemon('Delibird', False, False, 0, False),
        Pokemon('Gardevoir', False, False, 0, False),
        Pokemon('Hariyama', False, False, 0, False),
        Pokemon('Whiscash', False, False, 0, False),
        Pokemon('Banette', False, False, 0, False),
        Pokemon('Snorunt', False, False, 0, False),
        Pokemon('Glalie', False, False, 0, False),
        Pokemon('Bagon', False, True, 0, False),
        Pokemon('Floatzel', False, False, 0, False),
        Pokemon('Drifloon', True, False, 0, False),
        Pokemon('Drifblim', True, False, 0, False),
        Pokemon('Mismagius', False, True, 0, False),
        Pokemon('Bronzong', False, False, 0, False),
        Pokemon('Spiritomb', False, False, 0, False),
        Pokemon('Gabite', False, False, 0, False),
        Pokemon('Snover', False, False, 0, False),
        Pokemon('Abomasnow', False, False, 0, False),
        Pokemon('Weavile', False, False, 0, False),
        Pokemon('Glaceon', False, False, 0, False),
        Pokemon('Gallade', False, False, 0, False),
        Pokemon('Froslass', False, False, 0, False),
        Pokemon('Basculin', False, False, 0, False),
        Pokemon('Deerling', False, False, 0, False),
        Pokemon('Sawsbuck', False, False, 0, False),
        Pokemon('Cubchoo', False, False, 0, False),
        Pokemon('Beartic', False, False, 0, False),
        Pokemon('Cryogonal', False, False, 0, False),
        Pokemon('Rufflet', False, False, 0, False),
        Pokemon('Deino', True, False, 0, False),
        Pokemon('Zweilous', True, False, 0, False),
        Pokemon('Goomy', False, False, 0, False),
        Pokemon('Klefki', False, False, 0, False),
        Pokemon('Bergmite', False, False, 0, False),
        Pokemon('Avalugg', False, False, 0, False),
        Pokemon('Gumshoos', False, False, 0, False),
        Pokemon('Crabrawler', False, False, 0, False),
        Pokemon('Crabominable', False, False, 0, False),
        Pokemon('Lycanroc', False, False, 0, False),
        Pokemon('Lycanroc', False, False, 0, False),
        Pokemon('Mudsdale', False, False, 0, False),
        Pokemon('Salandit', False, False, 0, False),
        Pokemon('Drednaw', False, False, 0, False),
        Pokemon('Barraskewda', False, False, 0, False),
        Pokemon('Hattrem', False, False, 0, False),
        Pokemon('Snom', False, False, 0, False),
        Pokemon('Frosmoth', False, False, 0, False),
        Pokemon('Copperajah', False, False, 0, False),
        Pokemon('Dreepy', False, True, 0, False),
        Pokemon('Drakloak', False, True, 0, False),
        Pokemon('Lokix', False, False, 0, False),
        Pokemon('Naclstack', False, False, 0, False),
        Pokemon('Tadbulb', False, False, 0, False),
        Pokemon('Bellibolt', False, False, 0, False),
        Pokemon('Glimmet', False, False, 0, False),
        Pokemon('Greavard', False, False, 0, False),
        Pokemon('Houndstone', False, False, 0, False),
        Pokemon('Flamigo', False, False, 0, False),
        Pokemon('Cetoddle', False, False, 0, False),
        Pokemon('Cetitan', False, False, 0, False),
        Pokemon('Veluza', False, False, 0, False),
        Pokemon('Frigibax', False, False, 0, False),
    ]}
area_zero = {
    'name': 'Area Zero',
    'key': 'area_zero',
    'encounters': [
        Pokemon('Raichu', False, False, 0, False),
        Pokemon('Venomoth', False, False, 0, False),
        Pokemon('Dugtrio', False, False, 0, False),
        Pokemon('Golduck', False, False, 0, False),
        Pokemon('Hypno', False, False, 0, False),
        Pokemon('Chansey', False, False, 0, False),
        Pokemon('Vaporeon', False, False, 0, False),
        Pokemon('Jumpluff', False, False, 0, False),
        Pokemon('Espeon', False, False, 0, False),
        Pokemon('Umbreon', False, False, 0, False),
        Pokemon('Murkrow', False, False, 0, False),
        Pokemon('Girafarig', False, False, 0, False),
        Pokemon('Dunsparce', False, False, 0, False),
        Pokemon('Sneasel', False, False, 0, False),
        Pokemon('Phanpy', False, False, 0, False),
        Pokemon('Donphan', False, False, 0, False),
        Pokemon('Masquerain', False, False, 0, False),
        Pokemon('Sableye', False, False, 0, False),
        Pokemon('Meditite', False, False, 0, False),
        Pokemon('Medicham', False, False, 0, False),
        Pokemon('Numel', False, False, 0, False),
        Pokemon('Camerupt', False, False, 0, False),
        Pokemon('Swablu', False, False, 0, False),
        Pokemon('Altaria', False, False, 0, False),
        Pokemon('Buizel', False, False, 0, False),
        Pokemon('Floatzel', False, False, 0, False),
        Pokemon('Honchkrow', False, False, 0, False),
        Pokemon('Gible', False, False, 0, False),
        Pokemon('Gabite', False, False, 0, False),
        Pokemon('Weavile', False, False, 0, False),
        Pokemon('Pawniard', False, False, 0, False),
        Pokemon('Bisharp', False, False, 0, False),
        Pokemon('Braviary', False, False, 0, False),
        Pokemon('Deino', True, False, 0, False),
        Pokemon('Zweilous', True, False, 0, False),
        Pokemon('Volcarona', False, False, 0, False),
        Pokemon('Talonflame', False, False, 0, False),
        Pokemon('Floette', False, False, 0, False),
        Pokemon('Gogoat', False, False, 0, False),
        Pokemon('Hawlucha', False, False, 0, False),
        Pokemon('Lycanroc', False, False, 0, False),
        Pokemon('Lycanroc', False, False, 0, False),
        Pokemon('Salandit', False, False, 0, False),
        Pokemon('Salazzle', False, False, 0, False),
        Pokemon('Corviknight', False, False, 0, False),
        Pokemon('Frosmoth', False, False, 0, False),
        Pokemon('Cufant', False, False, 0, False),
        Pokemon('Copperajah', False, False, 0, False),
        Pokemon('Dreepy', False, True, 0, False),
        Pokemon('Drakloak', False, True, 0, False),
        Pokemon('Lokix', False, False, 0, False),
        Pokemon('Pawmi', False, False, 0, False),
        Pokemon('Pawmo', False, False, 0, False),
        Pokemon('Dachsbun', False, False, 0, False),
        Pokemon('Nacli', False, False, 0, False),
        Pokemon('Naclstack', False, False, 0, False),
        Pokemon('Garganacl', False, False, 0, False),
        Pokemon('Tadbulb', False, False, 0, False),
        Pokemon('Bellibolt', False, False, 0, False),
        Pokemon('Espathra', False, False, 0, False),
        Pokemon('Varoom', False, False, 0, False),
        Pokemon('Glimmet', False, False, 0, False),
        Pokemon('Glimmora', False, False, 0, False),
        Pokemon('Greavard', False, False, 0, False),
        Pokemon('Houndstone', False, False, 0, False),
        Pokemon('Flamigo', False, False, 0, False),
        Pokemon('Farigiraf', False, False, 0, False),
        Pokemon('Dudunsparce', False, False, 0, False),
        Pokemon('Great Tusk', True, False, 0, False),
        Pokemon('Scream Tail', True, False, 0, False),
        Pokemon('Brute Bonnet', True, False, 0, False),
        Pokemon('Flutter Mane', True, False, 0, False),
        Pokemon('Slither Wing', True, False, 0, False),
        Pokemon('Sandy Shocks', True, False, 0, False),
        Pokemon('Iron Treads', False, True, 0, False),
        Pokemon('Iron Bundle', False, True, 0, False),
        Pokemon('Iron Hands', False, True, 0, False),
        Pokemon('Iron Jugulis', False, True, 0, False),
        Pokemon('Iron Moth', False, True, 0, False),
        Pokemon('Iron Thorns', False, True, 0, False),
        Pokemon('Roaring Moon', True, False, 0, False),
        Pokemon('Iron Valiant', False, True, 0, False)
    ]
}
